### PR TITLE
Correct the remote for vendor files!

### PR DESCRIPTION
**Pull request by DroidThug**

### CODE REVIEW

**Comment by SferaDev** [comment]
Please don't spam PR like this in the future

**Comment by DroidThug** [comment]
@SferaDev Hello and sorry for 'spamming' the PR. 

But with due respect,  @TheCrazyLex had asked me to create pull requests in the first place. 

https://github.com/AOSPA/android_vendor_pa/pull/8

**Comment by SferaDev** [comment]
He said one commit which means one PR.

**Comment by SferaDev** [comment]
Anyway: 

Sony's: It was meant to be aospa remote (https://github.com/AOSPA/android_vendor_twrp-sony)
Nexus's: https://github.com/AOSPA/android_vendor_pa/commit/56a188a7d87a53f2b08a61178f90773f1120d8c3
Dragon: https://github.com/AOSPA/android_vendor_pa/commit/22d084859fd46b42a00bf6e2e810bd5b5e813eaa

**Comment by DroidThug** [comment]
Okay, sorry for PR, but I didn't mean to spam... I was only trying to help.

**Comment by SferaDev** [comment]
Yeah don't worry, hopefully we'll get gerrit up soon. It will be much better than PR.

**Comment by DroidThug** [comment]
Okay sure! I've grabbed lots of Snickers :P

**Pull request closed without merging**
