### PR TITLE
Correct the remote for vendor files!

### PR DESCRIPTION
**Pull request by DroidThug**

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
Can you do this for all devices which are being released? ^^

**Comment by DroidThug** [comment]
@TheCrazyLex Sure, but should I create Pull Requests for all of them?

**Comment by TheCrazyLex** [comment]
Thank you :) 
One pull request is ok. 
If you want you can also do another pull request for the marshmallow-caf branch :)

**Comment by DroidThug** [comment]
Okay sure :D
Btw, when will the Gerrit be up?

**Comment by DroidThug** [comment]
@TheCrazyLex could you make me a member temporarily?  I could use the terminal and update every branch! :D

**Pull request closed without merging**
