### PR TITLE
Submit new product: nubia v18 (NX612J)

### PR DESCRIPTION
**Pull request by gesangtome**

### CODE REVIEW

**Comment by Herna1994** [comment]
@Flowertome Does this device work properly? Have you booted oreo-mr1 for it?

**Comment by gesangtome** [comment]
@Herna1994 
It has been tested. But nougat-mr2 only. 
The device tree of oreo-mr1 is already being reconstructed, and I will upload it to aospa after passing the test

**Comment by Herna1994** [comment]
Nice! Once it´s ready please tell me and I will look for it, no need to PR changes, just upload device tree and such.

Also I will push the Pie manifest shortly, in case you wanna try it out. Most of platform changes are already pushed for Android 9.

**Comment by gesangtome** [comment]
@Herna1994 Thank you for the exciting news.

**Pull request closed without merging**
